title: CervejaBoavida
author:
  name: cefisys
  email: 'geral@cervejaboavida.pt'
metadata:
    description: 'Cerveja Boavida artesanal portuguesa'
    
# Site settings
title: cervejaBoavida
email: geral@cervejaBoavida.com


# Links to include in footer navigation
# For external links add external: true
links:
  - title: Oferta
    url: '#services'
  - title: Pecados
    url: '#portfolio'
  - title: Servicos
    url: '#about'
  - title: Cervejeiros
    url: '#team'
  - title: Contactos
    url: '#contact'            

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/boavidacervejaa?edit=true
  - title: facebook
    url: https://www.facebook.com/boavidacervejaartesanal/
  - title: instagram
    url: https://www.instagram.com/boavidacervejaartesanal/
  - title: github
    url: https://github.com/haviana/Boavida

routes:
#  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
#  /new/(.*): '/blog/$1'                     # Regex any /new/my-page URL to /blog/my-page Route
