title: cervejaBoavida
author:
  name: cefisys
  email: 'cefisys@gmail.com'
metadata:
    description: 'Cerveja Boavida artesanalmente portuguesa'
    
# Site settings
title: cervejaBoavida
email: geral@cervejaBoavida.com


# Links to include in footer navigation
# For external links add external: true
links:
  - title: Oferta
    url: '#oferta'
  - title: Pecados
    url: '#pecados'
  - title: Servicos
    url: '#servicos'
  - title: 'Cervejeiros'
    url: '#team'            

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: https://www.facebook.com/boavidacervejaartesanal/
  - title: instagram
    url: https://www.instagram.com/boavidacervejaartesanal/
  - title: github
    url: https://github.com/haviana/Boavida

